//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Se.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Withdraw
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int OldCash { get; set; }
        public int Cash { get; set; }
        public int NowCash { get; set; }
        public System.DateTime WithdrawTime { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> FinishTime { get; set; }
        public string UserName { get; set; }
    }
}
